#!/bin/sh
set -x
if [ -d /usr/share/man ] ; then
	mandir="--mandir=/usr/share/man"
fi
for i in /usr/kerberos /usr/local/kerberos /usr/local ; do
	if [ -d $i/include ] ; then CPPFLAGS="$CPPFLAGS -I$i/include"; fi
	if [ -d $i/lib ] ; then LDFLAGS="$LDFLAGS -L$i/lib"; fi
done
export LDFLAGS CPPFLAGS

sh ./configure --prefix=/usr --sysconfdir=/etc $mandir \
 --enable-ssl --enable-force_localhost \
 --enable-kerberos --enable-mit_kerberos4 \
     LDFLAGS="$LDFLAGS" CPPFLAGS="$CPPFLAGS"

exit 0
