#!/bin/sh
set -x
if [ -d /usr/share/man ] ; then
	mandir="--mandir=/usr/share/man"
fi
sh ./configure --prefix=/usr --sysconfdir=/etc $mandir \
 --disable-kerberos --enable-ssl --enable-force_localhost \
     LDFLAGS="$LDFLAGS" CPPFLAGS="$CPPFLAGS"

# Here are some more flags you may want:
#
# -L/usr/local/lib" CPPFLAGS="$CPPFLAGS -I/usr/local/include" \
# --enable-nls \
# --enable-kerberos --enable-mit_kerberos4 \
# --disable-ssl
# --disable-tcpwrappers
